gradRotate/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls import (
handler400, handler403, handler404, handler500
)




urlpatterns = [
    #path('admin/', admin.site.urls, name="admin"),
    path('', include('accounts.urls')),
    path('form/', include('users.urls', namespace='users')),
    path('dashboard/', include('dashboard.urls',namespace='dashboard')),
    path('admin_interface/', include('interface.urls', namespace = 'admin_interface')),

]

handler400 = 'accounts.views.bad_request'
handler403 = 'accounts.views.bad_request'
handler404 = 'accounts.views.bad_request'
handler500 = 'accounts.views.bad_request_500'

interface/urls.py
from django.urls import path
from interface import views



urlpatterns = [
    path('', views.admin_interface, name='admin_interface'),
    path('interns/', views.intern_interface, name='intern_interface'),
    path('allocate/', views.allocate_interface, name = 'allocate_interface'),
    path('allocate/excel', views.allocate_excel, name='allocate_excel'),
    path('jobs/', views.job_interface, name='job_interface'),
    path('deleteIntern/<int:pk>/', views.deleteIntern, name='deleteIntern' ),
    path('deleteJob/<int:pk>/', views.deleteJob, name='deleteJob' ),
    path('deleteOffice/<int:pk>/', views.deleteOffice, name='deleteOffice' ),
    path('deleteSkillComputing/<int:pk>/', views.deleteSkillComputing, name='deleteSkillComputing' ),
    path('deleteSkillAnalytic/<int:pk>/', views.deleteSkillAnalytic, name='deleteSkillAnalytic' ),
    path('deleteSkillMarketing/<int:pk>/', views.deleteSkillMarketing, name='deleteSkillMarketing' ),
    path('deleteSkillManagement/<int:pk>/', views.deleteSkillManagement, name='deleteSkillManagement' ),
    path('deleteSkillLeadership/<int:pk>/', views.deleteSkillLeadership, name='deleteSkillLeadership' ),
    path('deleteSkillBusiness/<int:pk>/', views.deleteSkillBusiness, name='deleteSkillBusiness' ),
    path('deleteSkillAdmin/<int:pk>/', views.deleteSkillAdmin, name='deleteSkillAdmin' ),
]

app_name = 'interface'

users/urls.py
from django.urls import path
from users import views

urlpatterns = [
    
    path('student_form/', views.student_form, name = "student_form"),
    path('student_form/requirements',views.student_form_requirements, name= 'student_form_requirements'),
    path('student_form/skills',views.student_form_skills, name= 'student_form_skills'),
    path('student_form/complete', views.student_complete, name= 'student_complete'),
    path('student_form/allocation/complete', views.student_allocation_complete, name= 'student_allocation_complete'),




    path('<int:pk>/manager_form/', views.manager_form, name='managerForm'),
    path('<int:pk>/manager_form/information', views.manager_form_requirements, name='managerForm2'),
    path('<int:pk>/manager_form/information_2', views.manager_form_additional_requirements, name='managerForm3'),
    path('<int:pk>/manager_form/skills', views.manager_form_skills, name='managerForm4'),
    path('<int:pk>/manager_form/complete', views.manager_complete, name='managerForm5'),
    path('manager_form/allocation/complete', views.manager_allocation_complete, name='manager_allocation_complete'),
    path('manager_dashboard/',views.manager_dashboard, name='manager_dashboard'),
    path('manager_form/create_job/', views.manager_create_job, name='manager_create_job'),
    path('<int:pk>/manager_form/delete_job/', views.manager_delete_job, name='managerDeleteJob'),
    path('<int:pk>/manager_form/duplicate_job/', views.manager_duplicate_job, name='managerDuplicateJob'),
]

app_name = 'users'

interface/models.py
from django.db import models

# Create your models here.

interface/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractBaseUser


from accounts.models import *

#Change phase form
class AdminForm(ModelForm):

    PHASES = (
        ('Job creation','Job creation'),
        ('Intern collection','Intern collection'),
        ('Allocation','Allocation'),
    )

    phase = forms.ChoiceField(choices = PHASES , widget=forms.RadioSelect(attrs={'class' : 'btn-check', 'onchange': 'submit();'}))

    class Meta:
        model = Admin
        fields = '__all__'
        exclude = ['name','user','allocation_algorithm','notify_allocations','total_jobs','total_interns','job_creation_date','intern_creation_date','allocation_creation_date','automate_phase']



#Change phase automatically on datetime
class AdminForm2(ModelForm):

    job_creation_date = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date', 'style':'color:#6c757d;'}))

    intern_creation_date = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date', 'style':'color:#6c757d;'}))

    allocation_creation_date = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date', 'style':'color:#6c757d;'}))

    automate_phase = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))
    
    class Meta:
        model = Admin
        fields = '__all__'
        exclude = ['name','user','allocation_algorithm','phase','notify_allocations','total_jobs','total_interns']

    def __init__(self, *args, **kwargs):
        super(AdminForm2, self).__init__(*args, **kwargs)
        self.fields['automate_phase'].required = False


#Toggle automated phase
class AdminToggleAutomaticPhase(ModelForm):

    class Meta:
        model = Admin
        fields = '__all__'
        exclude = ['name','user','allocation_algorithm','notify_allocations','total_jobs','total_interns','phase','job_creation_date','intern_creation_date','allocation_creation_date','automate_phase']



#Change allocation algorithm
class AdminToggleNotify(ModelForm):
    notify_allocations = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-check-input', 'onchange': 'submit();'}))
    
    ALGORITHM =(
        ('Gale Shapely','Gale Shapely'),
        ('Hungarian','Hungarian'),
        ('Pareto','Pareto'),
        ('Random Serial Dictatorship','Random Serial Dictatorship')

    )

    allocation_algorithm= forms.CharField(label='Allocation Algorithm: ', widget=forms.Select(choices=ALGORITHM))
    allocation_algorithm.widget.attrs.update({'class': 'form-select', 'onchange': 'submit();'})

    class Meta:
        model = Admin
        fields = '__all__'
        exclude = ['name','user','total_jobs','total_interns','phase','job_creation_date','intern_creation_date','allocation_creation_date','automate_phase']

    def __init__(self, *args, **kwargs):
        super(AdminToggleNotify, self).__init__(*args, **kwargs)
        self.fields['notify_allocations'].required = False


#Change allocation notification 
class AdminToggleAlgorithm(ModelForm):

    ALGORITHM =(
        ('Gale Shapely','Gale Shapely'),
        ('Hungarian','Hungarian'),
        ('Pareto','Pareto'),
        ('Random Serial Dictatorship','Random Serial Dictatorship')

    )

    allocation_algorithm= forms.CharField(label='Allocation Algorithm: ', widget=forms.Select(choices=ALGORITHM))
    allocation_algorithm.widget.attrs.update({'class': 'form-select'})

    class Meta:
        model = Admin
        fields = '__all__'
        exclude = ['name','user','notify_allocations','total_jobs','total_interns','phase','job_creation_date','intern_creation_date','allocation_creation_date','automate_phase']

interface/views.py
import json
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from accounts.models import *
from accounts.permissions import allowed_users, update_phase
from interface.forms import AdminForm, AdminForm2, AdminToggleAlgorithm, AdminToggleAutomaticPhase, AdminToggleNotify
from interface.gale_shapely import *
from interface.preferences import *
from users.forms import ManagerCreateOffice, ManagerCreateSkills
from users.models import *
from django.contrib import messages
from geopy.geocoders import Nominatim

# Create your views here.
import openpyxl


#Admin internface
@login_required(login_url='../../../../login')
@allowed_users(allowed_roles=['Admin'])
@update_phase
def admin_interface(request):

    #admin = request.user.admin
    admin = Admin.objects.all().first()
    jobs = Job.objects.all()
    users = User.objects.all().count()
    
    form = AdminForm(instance= admin)
    form2 = ManagerCreateOffice()
    additional_skills = ManagerCreateSkills()
    automatic_phase = AdminForm2(instance = admin)
    toggle_automatic_phase = AdminToggleAutomaticPhase(instance = admin)
    toggle_algorithm = AdminToggleAlgorithm(instance = admin)

    
    interns = Intern.objects.all()
    locations = JobLocation.objects.all()
    computing_skills = ComputingSkills.objects.all()
    analytic_skills = AnalyticSkills.objects.all()
    marketing_skills = MarketingSkills.objects.all()
    management_skills = ManagementSkills.objects.all()
    leadership_skills = LeadershipSkills.objects.all()
    business_skills = BusinessSkills.objects.all()
    admin_skills = AdminSkills.objects.all()
  
    context = { 'form': form, 
    'users':users,
    'jobs' :jobs , 
    'interns' : interns, 
    'locations' :locations, 
    'computing_skills' : computing_skills,
    'analytic_skills'  :analytic_skills,
    'marketing_skills' : marketing_skills,
    'management_skills' : management_skills,
    'leadership_skills' : leadership_skills,
    'business_skills' : business_skills,
    'admin_skills' : admin_skills,
    'additional_office':form2,
    'additional_skills': additional_skills,
    'automatic_phase':automatic_phase,
    'toggle_automatic_phase':toggle_automatic_phase,
    'toggle_algorithm':toggle_algorithm,
    'admin':admin
    }

    if request.method == 'POST':
        form = AdminForm(request.POST, instance= admin)  
        form2 =ManagerCreateOffice(request.POST)
        additional_skills =ManagerCreateSkills(request.POST)
        automatic_phase = AdminForm2(request.POST, instance = admin)
        toggle_automatic_phase = AdminToggleAutomaticPhase(request.POST, instance = admin)

        toggle_algorithm = AdminToggleAlgorithm(request.POST, instance= admin)

        if 'Submit_office' in request.POST:
            if form2.is_valid():
                office_name = form.data['location']
                address = form.data['address']
                try:
                    geolocator = Nominatim(user_agent="interface")
                    location = geolocator.geocode(address)
                    offices = JobLocation.objects.filter()
                    offices.create(location = office_name, address = location.address, latitude=location.latitude, longitude= location.longitude)
                except:
                    messages.error(request, 'Incorrect Address - Please submit a valid postcode for this address')
                    return redirect('../../../admin_interface')
                return redirect('../../../admin_interface')

        elif 'Submit_toggle_automated' in request.POST:
            if toggle_automatic_phase.is_valid():
                toggle_automatic_phase.save()
                return redirect('../../../admin_interface')



        elif 'Submit_phase' in request.POST:
            if automatic_phase.is_valid():
                #Changes the phases on the admin panel 

                allocation_creation_date = form.data['allocation_creation_date']
                intern_creation_date = form.data['intern_creation_date']
                job_creation_date = form.data['job_creation_date']
                if (job_creation_date >= intern_creation_date) or (intern_creation_date >= allocation_creation_date) or (job_creation_date >= allocation_creation_date):
    
                    messages.error(request, 'Incorrect Date Change Order - Please refer to the info button for more information')
                    return render(request, 'interface/interface.html', context)
                    
                else:
                    automatic_phase.save()
                    return redirect('../../../admin_interface')


                       
        elif 'Submit_skills' in request.POST:

            if additional_skills.is_valid():
                skill_category = form.data['skill_category']
                skill_name = form.data['name']

                if ComputingSkills.objects.filter(name = skill_name):
                        messages.info(request, str(skill_name) + ' already exists under computing skills!')
                elif AnalyticSkills.objects.filter(name = skill_name):
                        messages.info(request, str(skill_name) + ' already exists under analtyic skills!')
                elif ManagementSkills.objects.filter(name = skill_name):
                        messages.info(request, str(skill_name) + ' already exists under management skills!')
                elif MarketingSkills.objects.filter(name = skill_name):
                        messages.info(request, str(skill_name) + ' already exists under marketing skills!')
                elif LeadershipSkills.objects.filter(name = skill_name):
                        messages.info(request, str(skill_name) + ' already exists under leadership skills!')
                elif BusinessSkills.objects.filter(name = skill_name):
                        messages.info(request, str(skill_name) + ' already exists under business skills!')
                elif AdminSkills.objects.filter(name = skill_name):
                        messages.info(request, str(skill_name) + ' already exists under admin skills!')
                else:
                    if skill_category == 'Computing':
                        skills = ComputingSkills.objects.filter()
                    elif skill_category == 'Analytic':
                        skills = AnalyticSkills.objects.filter()
                    elif skill_category == 'Marketing':
                        skills = MarketingSkills.objects.filter()
                    elif skill_category == 'Management':
                        skills = ManagementSkills.objects.filter()
                    elif skill_category == 'Leadership':
                        skills = LeadershipSkills.objects.filter()
                    elif skill_category == 'Business':
                        skills = BusinessSkills.objects.filter()
                    elif skill_category == 'Admin':
                        skills = AdminSkills.objects.filter()
                    
                    skills.create(name = skill_name)
            
            return redirect('../../../admin_interface')
        
        elif 'Submit_algorithm' in request.POST:
            if toggle_algorithm.is_valid():
                toggle_algorithm.save()
                return redirect('../../../admin_interface')

       
       
        else:   
            if form.is_valid():
                form.save()

                
                
                return redirect('../../../admin_interface')


    
    return render(request, 'interface/interface.html', context)











#Admin Intern interface
@login_required(login_url='../../../../login')
@allowed_users(allowed_roles=['Admin'])
def intern_interface(request):
    
    
    interns = Intern.objects.all()
    jobs = Job.objects.all()

    intern_preference = intern_preference_dictionary()

    context = {'interns' : interns, 'jobs' :jobs , 'intern_preference' : intern_preference}
    return render(request, 'interface/interns.html', context)


#Admin Job interface
@login_required(login_url='../../../../login')
@allowed_users(allowed_roles=['Admin'])
def job_interface(request):
    
    jobs = Job.objects.all()
    interns = Intern.objects.all()

    job_preference = job_preference_dictionary()

    context = {'jobs' :jobs , 'interns' : interns, 'job_preference' : job_preference}
    return render(request, 'interface/jobs.html', context)

#This is to delete Interns from the system
@login_required(login_url='../../../../login')
@allowed_users(allowed_roles=['Admin'])
def deleteIntern(request, pk):

    
    intern = Intern.objects.get(id=pk)
    InternPreference.objects.filter(intern = intern).delete()
    User.objects.get(intern = intern).delete()
    intern.delete()
    #need to delete all interns items
    return redirect('../../../admin_interface/interns/')

@login_required(login_url='../../../../login')
@allowed_users(allowed_roles=['Admin'])
def deleteJob(request, pk):

    job = Job.objects.get(id=pk)
    InternPreference.objects.filter(job = job).delete()
    job.delete()
    return redirect('../../../admin_interface/jobs/')

@login_required(login_url='../../../../login')
@allowed_users(allowed_roles=['Admin'])
def deleteOffice(request, pk):
    office = JobLocation.objects.get(id=pk)
    office.delete()
    return redirect('../../../admin_interface')


@login_required(login_url='../../../../login')
@allowed_users(allowed_roles=['Admin'])
def deleteSkillComputing(request, pk):
    skill = ComputingSkills.objects.get(id=pk)
    skill.delete()
    return redirect('../../../admin_interface')

@login_required(login_url='../../../../login')
@allowed_users(allowed_roles=['Admin'])
def deleteSkillAnalytic(request, pk):
    skill = AnalyticSkills.objects.get(id=pk)
    skill.delete()
    return redirect('../../../admin_interface')

@login_required(login_url='../../../../login')
@allowed_users(allowed_roles=['Admin'])

interface/templates/interface/interns.html
{% extends "base.html" %} 


{% block content %}

<header>
    <title>Admin Interface | Gradrotate</title>
  </header>

<main>



    
    <div class = "sidebar active">
        <div class = "logo_content">
            
        </div>
        <ul class="nav_list" style="padding-left:22px;">
        <li>
            <a href="../../admin_interface"> 
                <i class='bx bx-grid-alt bx-sm'></i>
                <span class="links_name">Dashboard</span>
            </a>
        </li>
        <li>
            <a href="" class="active"> 
                <i class='bx bx-user bx-sm'></i>
                <span class="links_name">Interns</span>
            </a>
        </li>
        <li>
            <a href="../../../admin_interface/jobs"> 
                <i class='bx bx-briefcase bx-sm'></i>
                <span class="links_name">Jobs</span>
            </a>
        </li>
        </ul>
    </div>















    




    <div class="content">
        <div class="container-fluid" >
            <div class = "row justify-content-start" style="background-color: #E7E9EC;">
                <div class = "col-1">
                    <p class="h3"style = "padding: 5px 5px 5px; color:#565c62;">
                    <i class="fa fa-bars" id="btn1"></i>
                    </p>
                </div>
                
            </div>
            <script>
                let btn = document.querySelector("#btn1");
                let sidebar = document.querySelector(".sidebar");
                btn.onclick = function() {
                    sidebar.classList.toggle("active");
                }
                function checkWidth() {
                // Check if window width is less than 510px
                if (window.innerWidth < 510) {
                    // Remove "active" class from sidebar
                    sidebar.classList.remove("active");
                }
            }

            // Check width on page load
            window.onload = checkWidth();
            //or
            window.addEventListener('load',checkWidth);
            // add event listener for window resize
            window.addEventListener("resize", checkWidth);
            </script>
            <div class = "row pt-4 p-3">
                <h5 style="color: #6c757d;">
                    Dashboard > Interns
                </h5>
            </div>


            

            <div class = "row pt-1 p-3">
                
                <div class = "card card-body border-0  mb-5">
                    <div style = "overflow-y: auto;">
                    <table class="table" id="dtHorizontalVerticalExample" >
                        
                        <tr>
                            <th class="table-light">Name</th>
                            <th class="table-light">Email</th>

                            <th class="table-light">Progress</th>
                            <th class="table-light">Delete</th>
                            
                            {% for job in jobs %}
                                <th class="table-light">Pref. {{forloop.counter}}</th>
                            {% endfor %}

                            
                        </tr>
                    
                    <tbody>
                            {% for intern, jobs in intern_preference.items %}
                                <tr>
                                    <td style="min-width:100px">{{intern.name}}</td>
                                    <td style="min-width:100px">{{intern.email}}</td>

                                    <td style="min-width:150px">
                                        
                                        <progress value="{{intern.progress}}" max="5"> </progress>
                                        

                                        </td>
                                    <td style="min-width:100px"><a href="{% url 'interface:deleteIntern' intern.id %}">Delete</a></td>

                                    {% for job in jobs %}
                                        <td style="min-width:100px">{{job}}</td>
                                    {% endfor %}

                                    
                                    
      
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>   
                </div>
                    </div>
            </div>
        </div>
    </div>





</main> 

{% endblock %}
<script>
    $(document).ready(function () {
  $('#dtHorizontalVerticalExample').DataTable({
    "scrollX": true,
    "scrollY": 200,
  });
  $('.dataTables_length').addClass('bs-select');
});
</script>

interface/templates/interface/jobs.html
{% extends "base.html" %} 


{% block content %}

<header>
    <title>Admin Interface | Gradrotate</title>
  </header>

<main>



    <div class = "sidebar active">
        <div class = "logo_content">
            
        </div>
        <ul class="nav_list" style="padding-left:22px;">
        <li>
            <a href="../../admin_interface"> 
                <i class='bx bx-grid-alt bx-sm'></i>
                <span class="links_name">Dashboard</span>
            </a>
        </li>
        <li>
            <a href="../../../admin_interface/interns"> 
                <i class='bx bx-user bx-sm'></i>
                <span class="links_name">Interns</span>
            </a>
        </li>
        <li>
            <a href=""  class="active"> 
                <i class='bx bx-briefcase bx-sm'></i>
                <span class="links_name">Jobs</span>
            </a>
        </li>
        </ul>
    </div>




    <div class="content">
        <div class="container-fluid" >
            <div class = "row justify-content-start" style="background-color: #E7E9EC;">
                <div class = "col-1">
                    <p class="h3"style = "padding: 5px 5px 5px; color:#565c62;">
                    <i class="fa fa-bars" id="btn1"></i>
                    </p>
                </div>
                
                
            </div>
            <script>
                let btn = document.querySelector("#btn1");
                let sidebar = document.querySelector(".sidebar");
                btn.onclick = function() {
                    sidebar.classList.toggle("active");
                }
                function checkWidth() {
                // Check if window width is less than 510px
                if (window.innerWidth < 510) {
                    // Remove "active" class from sidebar
                    sidebar.classList.remove("active");
                }
            }

            // Check width on page load
            window.onload = checkWidth();
            //or
            window.addEventListener('load',checkWidth);
            // add event listener for window resize
            window.addEventListener("resize", checkWidth);
        
            </script>
            <div class = "row pt-4 p-3">
                <h5 style="color: #6c757d;">
                    Dashboard > Jobs
                </h5>
            </div>
            
            <div class = "row pt-1 p-3">
                <div class = "card card-body border-0  mb-5">
                    <div style = "overflow-y: auto;">
                    <table class="table" id="dtHorizontalVerticalExample" >
                        <tr>
                            <th class="table-light">Job</th>
                            <th class="table-light">Manager Name</th>
                            <th class="table-light">Manager Email</th>

                            <th class="table-light">Progress</th>
                            <th class="table-light">Delete</th>

                            {% for intern in interns %}
                                <th class="table-light">Pref. {{forloop.counter}}</th>
                            {% endfor %}

                            
                        </tr>

                        <tbody>
                            {% for job, interns in job_preference.items %}
                                <tr>
                                    <td style="min-width:100px">{{job.name}}</td>
                                    <td style="min-width:100px">{{job.manager_name}}</td>
                                    <td style="min-width:100px">{{job.email}}</td>

                                    <td style="min-width:150px">
                                        
                                        <progress value="{{job.progress}}" max="5"> </progress>
                                        
                                        </td>
                                    <td style="min-width:100px"><a href="{% url 'interface:deleteJob' job.id %}">Delete</a></td>

                                    {% for intern in interns %}
                                        <td style="min-width:100px">{{intern}}</td>
                                    {% endfor %}

                                    
                                    
      
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    </div>

                    
                </div>
                        
                </div>
            </div>
        </div>
    </div>

</main> 

{% endblock %}