gradRotate/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls import (
handler400, handler403, handler404, handler500
)




urlpatterns = [
    #path('admin/', admin.site.urls, name="admin"),
    path('', include('accounts.urls')),
    path('form/', include('users.urls', namespace='users')),
    path('dashboard/', include('dashboard.urls',namespace='dashboard')),
    path('admin_interface/', include('interface.urls', namespace = 'admin_interface')),

]

handler400 = 'accounts.views.bad_request'
handler403 = 'accounts.views.bad_request'
handler404 = 'accounts.views.bad_request'
handler500 = 'accounts.views.bad_request_500'

users/urls.py
from django.urls import path
from users import views

urlpatterns = [
    
    path('student_form/', views.student_form, name = "student_form"),
    path('student_form/requirements',views.student_form_requirements, name= 'student_form_requirements'),
    path('student_form/skills',views.student_form_skills, name= 'student_form_skills'),
    path('student_form/complete', views.student_complete, name= 'student_complete'),
    path('student_form/allocation/complete', views.student_allocation_complete, name= 'student_allocation_complete'),




    path('<int:pk>/manager_form/', views.manager_form, name='managerForm'),
    path('<int:pk>/manager_form/information', views.manager_form_requirements, name='managerForm2'),
    path('<int:pk>/manager_form/information_2', views.manager_form_additional_requirements, name='managerForm3'),
    path('<int:pk>/manager_form/skills', views.manager_form_skills, name='managerForm4'),
    path('<int:pk>/manager_form/complete', views.manager_complete, name='managerForm5'),
    path('manager_form/allocation/complete', views.manager_allocation_complete, name='manager_allocation_complete'),
    path('manager_dashboard/',views.manager_dashboard, name='manager_dashboard'),
    path('manager_form/create_job/', views.manager_create_job, name='manager_create_job'),
    path('<int:pk>/manager_form/delete_job/', views.manager_delete_job, name='managerDeleteJob'),
    path('<int:pk>/manager_form/duplicate_job/', views.manager_duplicate_job, name='managerDuplicateJob'),
]

app_name = 'users'

users/models.py
from django.db import models
from accounts.models import Job





#Intern preferences displayed here
class InternPreference(models.Model):

    intern = models.ForeignKey("accounts.Intern", null = True, on_delete = models.SET_NULL)
    job = models.ForeignKey("accounts.Job", null = True, blank = True, on_delete = models.SET_NULL)
    date_created = models.DateTimeField(auto_now_add = True, null = True)


  
    jobs = Job.objects.all()
    

    preference = models.IntegerField(blank=True)

users/views.py
from email.policy import HTTP
from unicodedata import name
from django.shortcuts import render , redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from accounts.permissions import allowed_users, required_phase, update_progress
from users.models import InternPreference
from .forms import *
from django.contrib import messages
import json 
from geopy.geocoders import Nominatim



# Create your views here.

@login_required(login_url='../../../../login')
@allowed_users(allowed_roles=['Intern'])
@update_progress(1)
@required_phase(phase=['Intern collection'])
def student_form(request):
    intern = request.user.intern
    form = StudentForm(instance= intern)
    

    if request.method == 'POST':
        form = StudentForm(request.POST, instance= intern)        
        if form.is_valid():
            

            form.save()
            return redirect('../../form/student_form/requirements')


    context = {'form': form, 'intern': intern}
    return render(request, 'users/student_form.html', context)
    


@login_required(login_url='../../../../login')
@allowed_users(allowed_roles=['Intern'])
@update_progress(2)
@required_phase(phase=['Intern collection'])
def student_form_requirements(request):
    intern = request.user.intern
    form = StudentForm2(instance= intern)
    
    location_list = list(JobLocation.objects.all().values()) 
    location_json = json.dumps(location_list)
    
    if request.method == "POST":
        form = StudentForm2(request.POST, instance= intern) 
        if form.is_valid():
            
            form.save()
            return redirect('../../form/student_form/skills')

    context = {'form': form, 'intern': intern, 'locations': location_json}
    return render(request, 'users/student_form2.html', context)



@login_required(login_url='../../../../login')
@allowed_users(allowed_roles=['Intern'])
@update_progress(3)
@required_phase(phase=['Intern collection'])
def student_form_skills(request):
    intern = request.user.intern
    form = StudentForm3(instance= intern)

    computing_skills = ComputingSkills.objects.all()

    if request.method == "POST":
        form = StudentForm3(request.POST, instance= intern) 
        if form.is_valid() and 'Submit' in request.POST:
            #gathers all the skills

            computing_skills = form.cleaned_data['computing_skills']
            analytic_skills = form.cleaned_data['analytic_skills']
            marketing_skills = form.cleaned_data['marketing_skills']
            management_skills = form.cleaned_data['management_skills']
            leadership_skills = form.cleaned_data['leadership_skills']
            business_skills = form.cleaned_data['business_skills']
            admin_skills = form.cleaned_data['admin_skills']

            

            if (len(computing_skills) + len(analytic_skills) + len(marketing_skills) + len(management_skills) + len(leadership_skills) +len(business_skills)+len(admin_skills)) > 5:
                messages.info(request, '5 Skill maximum')
                context = {'form': form, 'intern': intern}
                return render(request, 'users/student_form3.html', context)
            else:
                
                form.save()
                return redirect('../../dashboard')

        else:
            messages.info(request, 'Error completing form')
            context = {'form': form, 'intern': intern}
            return render(request, 'users/student_form3.html', context)


    context = {'form': form, 'intern': intern}
    return render(request, 'users/student_form3.html', context)





    
@login_required(login_url='../../../../login')
@allowed_users(allowed_roles=['Manager'])
@required_phase(phase=['Job creation'])
def manager_form(request, pk):
    #job = request.user.job
    job = Job.objects.get(id=pk)
    manager = request.user.manager

    if job.manager != manager:
        return redirect('../../../../../form/manager_dashboard')

    
    

    if job.progress < 1:
        job.progress = 1
        job.save()

    #.job
    form = ManagerForm(instance= job)


    if request.method == 'POST':
        
        form = ManagerForm(request.POST, instance= job)     
 

        if form.is_valid() and 'Submit_form' in request.POST:
            
            form.save()
            return redirect('../../../form/'+str(job.id)+'/manager_form/information')


    context = {'form': form, 'job': job}
    return render(request, 'users/manager_form.html', context)





@login_required(login_url='../../../../login')
@allowed_users(allowed_roles=['Manager'])
@required_phase(phase=['Job creation'])
def manager_form_requirements(request, pk):
    #job = request.user.job
    job = Job.objects.get(id=pk)
    manager = request.user.manager

    if job.manager != manager:
        return redirect('../../../../../form/manager_dashboard')

    if job.progress < 2:
        job.progress = 2
        job.save()

    form = ManagerForm2(instance= job)

    location_list = list(JobLocation.objects.all().values()) 
    location_json = json.dumps(location_list)

    if request.method == 'POST':
        form = ManagerForm2(request.POST, instance= job)        
        if form.is_valid():
            #gathers all the skills
            form.save()
            return redirect('../../../form/'+str(job.id)+'/manager_form/information_2')

    context = {'form': form, 'job': job, 'locations': location_json}
    return render(request, 'users/manager_form2.html', context)



    
@login_required(login_url='../../../../login')
@allowed_users(allowed_roles=['Manager'])
@required_phase(phase=['Job creation'])
def manager_form_additional_requirements(request, pk):
    
    job = Job.objects.get(id=pk)
    manager = request.user.manager

    if job.manager != manager:
        return redirect('../../../../../form/manager_dashboard')

    if job.progress < 3:
        job.progress = 3
        job.save()

    form = ManagerForm4(instance= job)
    form2 = ManagerCreateOffice()

    location_list = list(JobLocation.objects.all().values()) 
    location_json = json.dumps(location_list)
    




    if request.method == 'POST':

        form = ManagerForm4(request.POST, instance= job)   
        form2 =ManagerCreateOffice(request.POST)  
        if 'Submit_office' in request.POST:
            if form2.is_valid():
                office_name = form.data['location']
                address = form.data['address']
                try:
                    geolocator = Nominatim(user_agent="users")
                    location = geolocator.geocode(address)
                    offices = JobLocation.objects.filter()
                    offices.create(location = office_name, address = location.address, latitude=location.latitude, longitude= location.longitude)
                except:

                    messages.info(request, 'Incorrect Address - Please submit a valid postcode for this Address!')
                    context = {'form': form, 'additional_office': form2, 'job': job, 'locations': location_json}
                    return redirect('../../../form/'+str(job.id)+'/manager_form/information_2')
                    
                    

                return redirect('../../../form/'+str(job.id)+'/manager_form/information_2')

        elif 'Submit_form' in request.POST:   
            if form.is_valid():
                #gathers all the skills
                job.wage = form.data['wage_value']
                form.save()
                return redirect('../../../form/'+str(job.id)+'/manager_form/skills')

        


                

    context = {'form': form, 'additional_office': form2, 'job': job, 'locations': location_json}
    return render(request, 'users/manager_form4.html', context)






@login_required(login_url='../../../../login')
@allowed_users(allowed_roles=['Manager'])
@required_phase(phase=['Job creation'])
def manager_form_skills(request, pk):
    job = Job.objects.get(id=pk)
    manager = request.user.manager

    if job.manager != manager:
        return redirect('../../../../../form/manager_dashboard')

    if job.progress < 4:
        job.progress = 4
        job.save()

    form = ManagerForm3(instance= job)
    additional_skills = ManagerCreateSkills()

    if request.method == 'POST':
        form = ManagerForm3(request.POST, instance= job)      

        additional_skills =ManagerCreateSkills(request.POST)
        if 'Submit_skills' in request.POST:

            if additional_skills.is_valid():
                skill_category = form.data['skill_category']
                skill_name = form.data['name']

                if ComputingSkills.objects.filter(name = skill_name):
                        messages.info(request, str(skill_name) + ' already exists under computing skills!')
                elif AnalyticSkills.objects.filter(name = skill_name):
                        messages.info(request, str(skill_name) + ' already exists under analtyic skills!')
                elif ManagementSkills.objects.filter(name = skill_name):
                        messages.info(request, str(skill_name) + ' already exists under management skills!')
                elif MarketingSkills.objects.filter(name = skill_name):
                        messages.info(request, str(skill_name) + ' already exists under marketing skills!')
                elif LeadershipSkills.objects.filter(name = skill_name):
                        messages.info(request, str(skill_name) + ' already exists under leadership skills!')
                elif BusinessSkills.objects.filter(name = skill_name):
                        messages.info(request, str(skill_name) + ' already exists under business skills!')
                elif AdminSkills.objects.filter(name = skill_name):
                        messages.info(request, str(skill_name) + ' already exists under admin skills!')
                else:
                    
                    if skill_category == 'Computing':

users/templates/users/manager_complete.html
{% extends "base.html" %}


{% block content %}

<header>
    <title>{{job.name}} | Gradrotate</title>
  </header>


<main>
    <div class = "progress-with-nav">
        <div class="progress">
            <div class="progress-bar " role="progressbar" style="width: 80%; background-color: #5A9B95;" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
            <div class="progress-bar " role="progressbar" style="width: 20%; background-color:#294b63" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
    </div>
    <div class="container-fluid p-0 m-0">
        <div class = 'title-bar text-center'>
            <div class = "row justify-content-center">
            <h3 style="margin-top: 50px;">{{job.name}}</h3>
            </div>
        </div>
        

        <div class="row">
        <div class="card border-0 rounded m-4 p-4 mx-auto" style="max-width: 45rem;">
            <div class="row">
                <div class="col-2">
                    <div class="text-center">
                        <i class='bx bx-lg bx-check-circle'></i>
    
                    </div>
    
                </div>
                <div class = "col-10">

                    Your job has been saved successfully! Once the allocation phase is complete, you will receive the details of your allocated intern.
                </div>
                    
    
            </div>
               
                    
                
            </div>
        </div>
        
        <div class="row" style="padding-bottom: 70px;">

        
            <div class="card border-0 rounded m-4 pt-1 mb-0 pb-0 mx-auto" style="max-width: 70rem;">
                <div class="row d-flex justify-content-center p-0">
                    
                        <a href="{% url 'users:managerForm' job.id %}" class="save-button p-2 m-2 text-center" style="display: inline;text-decoration:none;">Edit Job</a>
                    
        
                   
                   
                        <a href="{% url 'users:managerForm4' job.id %}" class="save-button p-2 m-2 text-center" style="display: inline;text-decoration:none">Edit Skills</a>
                    
        
                   
                  
                        <a href="{% url 'users:managerDuplicateJob' job.id %}" class="back-button p-2 m-2 text-center" style="display: inline;text-decoration:none">Duplicate Job</a>
                    
        
               
                    
                 
                        
                        <button type="button" class="back-button p-2 m-2 text-center" data-bs-toggle="modal" data-bs-target="#modal-1">
                            Delete Job
                        </button>


                        <div class="modal fade justify-content-center" id="modal-1" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered modal-md">
                            <div class="modal-content">
                                <div class="modal-header" style="display: block;">
                                    <div class="row text-center">   
                                        <h4 class= "job-card-title-text " > Delete Job</h4> 
                                      
                                    </div>
                                    
                                </div>
                                    
                                <div class="modal-body">
                                    <div class="container-fluid">
                                        <div class="row">
                                            Are you sure you want to delete Job {{job.name}}?
                                        </div>
                                        
                                        
                                    </div>

                                </div>
                                <div class="modal-footer">
                                    <a href="{% url 'users:managerDeleteJob' job.id %}" class="save-button p-2 m-1 text-center" style="display: inline;text-decoration:none; width: 120px;">Delete</a>
                    
                                    <button type="button" class="back-button p-2 m-1 text-center" style="display: inline;text-decoration:none; width: 120px;" data-bs-dismiss="modal">Cancel</button>
                                </div>
                            </div>

                  
                    

                </div>
            
                        </div>




            <div class="card shadow-sm border-0 rounded m-4 mt-0 p-4 mx-auto" style="max-width: 70rem;">
                 
                <div class="job-card-body">
                    



                    <div class="row">
                        <div class="col-lg-7">
                            <div class="row pt-2">
                                <div class="question-text float-start">
                                    Description:
                                </div>

                            </div>
                            <div class="row pt-2">
                                <div style="padding-left: 12px; padding-right: 12px;">
                                    {{job.description|linebreaks}}
                                
                                </div>
                                

                            </div>
                            <div class="row pt-2">
                                <div class="question-text">
                                    Daily Tasks:
                                </div>

                            </div>
                            <div class="row pt-2">
                                <div style="padding-left: 12px; padding-right: 12px;">
                                    {{job.daily_tasks|linebreaks}}
                                </div>
                               

                            </div>
                            
                            
                            

                            



                        </div>
                        <div class="col-lg-5">
                            
                                <div class="question-text">
                                    Key Skills:
                                </div>
                                    {% for skill in skills %}
                                    <button type="button" class="skill-button">{{skill}}</button>

                                        {% endfor %}
                                
                               

                           
                            
                            <div class="row pt-3">
                                <div class="col-5">
                                    <div class="question-text float-start">
                                        Location: 
                                    </div>
                                </div>
                                <div class="col">
                                    <div class = "">
                                        {{job.job_location.location}}
                                    </div>
                                </div>
                                
                            </div>
                            <div class="row pt-3">
                                <div class="col-5">
                                    <div class="question-text float-start">
                                        Team: 
                                    </div>
                                </div>
                                <div class="col">
                                    <div class = "">
                                       
                                        {{job.team}}
                                    </div>
                                </div>
                                
                            </div>

                            <div class="row pt-3">
                                <div class="col-5">
                                    <div class="question-text float-start">
                                        Remote Balance: 
                                    </div>
                                </div>
                                <div class="col">
                                    <div class = "">
                                       
                                        {{job.remote}} (Days In The Office A Week)
                                    </div>
                                </div>
                                
                            </div>

                            <div class="row pt-3">
                                <div class="col-5">
                                    <div class="question-text float-start">
                                        Wage: 
                                    </div>
                                </div>
                                <div class="col">
                                    <div class = "">
                                       
                                        £{{job.wage}}
                                    </div>
                                </div>
                                
                            </div>
                            <div class="row pt-3">
                                <div class="col-5">
                                    <div class="question-text float-start">
                                        Manager's Name: 
                                    </div>
                                </div>
                                <div class="col">
                                    <div class = "">
                                       
                                        {{job.manager_name}}
                                    </div>
                                </div>
                                
                            </div>
                            <div class="row pt-3">
                                <div class="col-5">
                                    <div class="question-text float-start">
                                        Manager's Email: 
                                    </div>
                                </div>
                                <div class="col">
                                    <div class = "">
                                       
                                        {{job.email }}
                                    </div>
                                </div>
                                
                            </div>

                            
                        
                            
                            

                            


                            

                        </div>
                    </div>


                </div>
            </div>
        </div>
        

    </div>
    
    <div class="save-bar">
        <div style = "display: flex; justify-content: center; ">        
                
            <a href="../../../../form/manager_dashboard/" class="back-button p-2 m-2 text-center" style="display: inline;text-decoration:none">Return to dashboard</a>
               
                
              
        </div>
    </div>

</main>
{% endblock %}

users/templates/users/manager_dashboard.html
{% extends "base.html" %}


{% block content %}


<header>
    <title>Allocation | Gradrotate</title>
  </header>


<main>
    <div class = "progress-with-nav">
        <div class="progress">
            <div class="progress-bar " role="progressbar" style="width: 0%; background-color: #5A9B95;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
    </div>
    <div class="container-fluid p-0 m-0">
        <div class = 'title-bar text-center'>
            <div class = "row justify-content-center">
            <h3 style="margin-top: 50px;">Manager Dashboard</h3>
            </div>
        </div>

    


    

    <div class="row justify-content-center m-2">
        <div class="col-sm-12 col-md-8 col-lg-6 col-xl-5">
            


        
            {% for job in manager_jobs %}
            <a href="{% url 'users:managerForm5' job.id %}" class="pb-2" style="color: black;text-decoration:none">

            
                <div class="job-card shadow-sm border-0 m-2" >
                    <h5 class="job-card-title">
                        <div class="row">
                            
                            
                            
                                <div class=" text-center job-card-title-text">
                                    {{job.name}}
                                </div>
                                
                            
                        
                        </div>
                    </h5>   
                    <div class="job-card-body m-2">
                        
                        <div class="row pt-3" style="max-height: 50px;">
                            <div class="col-9">
                                <div class="card-description">
                                    {{job.description}}
                                </div>                   
                                                    
                            </div>
                            <div class="col-3">
                                <div class="card-description pt-2">
                                    <i class="fa fa-sharp fa-solid fa-lg fa-location-dot float-start" style = "color: #294b63;"></i>
                                
                                    
                                    {{job.job_location.location}}
                                </div>
                                
                            </div>
                        </div>
                        <div class="row" style="max-height: 50px;">
                            <div class="col-9">
                                

                            </div>
                            <div class="col-3">
                                
                                <div class="card-description pt-2">
                                    <i class=" fa fa-solid fa-lg fa-users" style = "color: #294b63;"></i>
                                    {{job.team}}

                                </div>
                                
                            </div>

                        </div>
                



                        
                        </div>
                

                </div>
            </a>
            {% endfor %}

            <div class="row justify-content-center m-5">
            <a href="../../../../form/manager_form/create_job/" class="save-button p-2 m-2 text-center" style="display: inline;text-decoration:none">+ Create New Job</a>
        
        </div>
        </div>
    </div>


   
                
    </div>

</main>
{% endblock %}

users/templates/users/manager_form2.html
{% extends "base.html" %}


{% block content %}
<header>
    <title>Job Form | Gradrotate</title>
  </header>


<main>

    <div class = "progress-with-nav">
        <div class="progress">
            <div class="progress-bar " role="progressbar" style="width: 40%; background-color: #5A9B95;" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
    </div>

    <div class="container-fluid p-0 m-0">
        <div class = 'title-bar text-center'>
            <div class = "row justify-content-center">
            <h3 style="margin-top: 50px;">Job information</h3>
            </div>
    </div>
<div class="container">

    
    

<form method="POST" action="">

    {% csrf_token %}

    



    
    
    <row>
        <div class="card shadow-sm border-0 rounded m-4 p-4 mx-auto" style="max-width: 45rem;">
            <div class="card-body">
            <div class="question-text">Job name *</div>
            
            {{form.name}}
            </div>
            
        </div>

    </row>
    <row>
        <div class="card shadow-sm border-0 rounded m-4 p-4 mx-auto" style="max-width: 45rem;">
            <div class="card-body">
            <div class="question-text">Job description *</div>
            
            {{form.description}}
            </div>
            
    </div>
    <row>
        <div class="card shadow-sm border-0 rounded ml-4 mr-4 mt-4 p-4 mx-auto" style="max-width: 45rem;margin-bottom: 100px;">
            <div class="card-body">
            <div class="question-text">Job's daily tasks *</div>
            {{form.daily_tasks}}
            </div>
            
    </div>





    {{form.errors}}
    <div class="save-bar">
        <div style = "display: flex;
        justify-content: center; ">
    
            
                <a href="{% url 'users:managerForm' job.id %}" class="back-button p-2 m-2 text-center" style="display: inline;text-decoration:none">Back</a>
                
        
                
            
                <button class="save-button p-2 m-2" type="submit" name ="Submit" value="Next">Save and continue</button>
                
              
        </div>
    </div>
 
</form>
</div>   

</main>


{% endblock %}